# HAL server PORTS
HAL_REST_PORT = 54331
HAL_WS_PORT = 54332

# HAL URL paths
HAL_BASE_URL_PATH = '/hal'

# HAL REST HTTP Response status codes
NOT_FOUND_HTTP_RESPONSE_CODE = 404
ERROR_HTTP_RESPONSE_CODE = 500
OK_HTTP_RESPONSE_CODE = 200

# HAL WS common OPCODEs
HAL_WS_OPEN_CONNECTION_OPCODE = 3
HAL_WS_CONNECTION_OPENED_OPCODE = 4
HAL_WS_SEND_DATA_OPCODE = 5
HAL_WS_GOT_DATA_OPCODE = 6
# HAL WS closing frame status code
HAL_WS_CLOSE_FRAME_STATUS_NORMAL = 1000
HAL_WS_CLOSE_FRAME_STATUS_EXCEPTION = 4000

# HTTP requests utils
HTTP_PROTOCOL = 'http'
HOST = 'localhost'
APPLICATION_JSON = 'application/json'
# WS request utils
WS_REQUEST_URL_PATTERN = 'ws://{}:{}'

# HAL URL paths for USB-to-Serial
HAL_USB_TO_SERIAL_BASE_PATH = HAL_BASE_URL_PATH + '/rs232'
HAL_USB_TO_SERIAL_GET_LIST_PATH = HAL_USB_TO_SERIAL_BASE_PATH + '/list'
# HAL USB-to-Serial config property names
HAL_USB_TO_SERIAL_PORT_PROPERTY_NAME = 'port'
HAL_USB_TO_SERIAL_BAUDRATE_PROPERTY_NAME = 'baudrate'
HAL_USB_TO_SERIAL_BYTESIZE_PROPERTY_NAME = 'bytesize'
HAL_USB_TO_SERIAL_PARITY_PROPERTY_NAME = 'parity'
HAL_USB_TO_SERIAL_STOPBITS_PROPERTY_NAME = 'stopbits'
HAL_USB_TO_SERIAL_TIMEOUT_PROPERTY_NAME = 'timeout'
HAL_USB_TO_SERIAL_XONXOFF_PROPERTY_NAME = 'xonxoff'
HAL_USB_TO_SERIAL_RTSCTS_PROPERTY_NAME = 'rtscts'
HAL_USB_TO_SERIAL_DSRDTR_PROPERTY_NAME = 'dsrdtr'
HAL_USB_TO_SERIAL_WRITE_TIMEOUT_PROPERTY_NAME = 'write_timeout'
HAL_USB_TO_SERIAL_INTER_BYTE_TIMEOUT_PROPERTY_NAME = 'inter_byte_timeout'

# HWC cmd names commands
LSCPU = 'lscpu'
LSPCI = 'lspci'
LSHW = 'lshw'
LSUSB = 'lsusb'
PROC = '/proc/{}'
CPU_INFO = 'cpuinfo'

# HWC REST URL paths
HAL_HWC_BASE_URL = HAL_BASE_URL_PATH + '/hwc'
HAL_HWC_GET_LSCPU_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSCPU
HAL_HWC_GET_CPU_INFO_PATH = HAL_HWC_BASE_URL + PROC.format(CPU_INFO)
HAL_HWC_GET_LSPCI_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSPCI
HAL_HWC_GET_LSHW_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSHW
HAL_HWC_GET_LSUSB_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSUSB
